import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav'
import getWord from './api/GetWord'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  let firstWord = getWord()
  console.log(firstWord)
  const handleStartGame = (e) => {
    e.preventDefault()
    router.push('/hangman')

  }

  return (
    <>
      <div>
        <Head>
          <title>Hangman App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />

      </div>
      <div className='start-button-div'>
        <button className='start-button' onClick={handleStartGame}>Start Game</button>
      </div>
     
  
    </>
  )
}
